export const GROUPS = "Groups";
export const CREATE_GROUP = "Create Group";
export const VIEW_GROUP = "View Group";
export const CREATE_MEETING_REQUEST = "Create Meeting Request"; 
export const ADD_MEMBERS = "Add Members";
export const GROUP = "Group";
export const NOTIFICATIONS = "Notifications";
export const REFERENCE = "Reference";
export const VIEW_POLL = "View Poll";
